import type { Metadata } from "next";
import "@picocss/pico"

export const metadata: Metadata = {
  title: "dodo - hello nextjs (with dodo)",
  description: "Generated by dodo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container">
        <header>
          <nav>
            <ul>
              <li><strong><a href="/">dodo: Blog!</a></strong></li>
            </ul>
            <ul>
              <li><a href="/create" role="button">Create Entry</a></li>
            </ul>
          </nav>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
